# Build for amd64 and arm64 and publish to DockerHub and GitHub Packages
# Bleeding edge of main published as :alpha
# The :alpha image is automatically re-built and pushed fortnightly to include changes to upstream images

name: :alpha

on:
  push:
    branches: 
      - 'main'
  schedule:
    - cron: "37 1 */1,*/14 * *"

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3.3.0
        
      - name: Setup buildx
        uses: docker/setup-buildx-action@v3.8.0
      
      - name: Log in to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Log in to the GitHub Packages container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            fetzu/teslamate-abrp
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=beta
          flavor: |
            latest=false
          
      - name: Build and push Docker image with 'alpha' tag
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            fetzu/teslamate-abrp:alpha,
            ghcr.io/${{ github.repository }}:alpha
          labels: ${{ steps.meta.outputs.labels }}
